// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Honeycomb.Resources
{
    [HoneycombResourceType("honeycomb:Resources:Column")]
    public partial class Column : global::Pulumi.CustomResource
    {
        [Output("columnId")]
        public Output<string> ColumnId { get; private set; } = null!;

        [Output("dataset")]
        public Output<string> Dataset { get; private set; } = null!;

        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        [Output("hidden")]
        public Output<bool> Hidden { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a Column resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Column(string name, ColumnArgs args, CustomResourceOptions? options = null)
            : base("honeycomb:Resources:Column", name, args ?? new ColumnArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Column(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("honeycomb:Resources:Column", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/martinjt/honeycomb-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Column resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Column Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Column(name, id, options);
        }
    }

    public sealed class ColumnArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataset", required: true)]
        public Input<string> Dataset { get; set; } = null!;

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("hidden")]
        public Input<bool>? Hidden { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("type", required: true)]
        public Input<Pulumi.Honeycomb.Resources.ColumnType> Type { get; set; } = null!;

        public ColumnArgs()
        {
        }
        public static new ColumnArgs Empty => new ColumnArgs();
    }
}
