// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.Honeycomb.Resources
{
    [EnumType]
    public readonly struct ColumnType : IEquatable<ColumnType>
    {
        private readonly string _value;

        private ColumnType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// String Columns are the catch all
        /// </summary>
        public static ColumnType @String { get; } = new ColumnType("string");
        /// <summary>
        /// Int Columns are for integers
        /// </summary>
        public static ColumnType Integer { get; } = new ColumnType("integer");
        /// <summary>
        /// Float Columns are for floats
        /// </summary>
        public static ColumnType @Float { get; } = new ColumnType("float");
        /// <summary>
        /// Boolean Columns are for booleans
        /// </summary>
        public static ColumnType Boolean { get; } = new ColumnType("boolean");

        public static bool operator ==(ColumnType left, ColumnType right) => left.Equals(right);
        public static bool operator !=(ColumnType left, ColumnType right) => !left.Equals(right);

        public static explicit operator string(ColumnType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ColumnType other && Equals(other);
        public bool Equals(ColumnType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
