// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ColumnArgs } from "./column";
export type Column = import("./column").Column;
export const Column: typeof import("./column").Column = null as any;
utilities.lazyLoad(exports, ["Column"], () => require("./column"));

export { DatasetArgs } from "./dataset";
export type Dataset = import("./dataset").Dataset;
export const Dataset: typeof import("./dataset").Dataset = null as any;
utilities.lazyLoad(exports, ["Dataset"], () => require("./dataset"));


// Export enums:
export * from "../types/enums/resources";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "honeycomb:resources:Column":
                return new Column(name, <any>undefined, { urn })
            case "honeycomb:resources:Dataset":
                return new Dataset(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("honeycomb", "resources", _module)
