// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ColumnType = {
    /**
     * String Columns are the catch all
     */
    String: "string",
    /**
     * Int Columns are for integers
     */
    Integer: "integer",
    /**
     * Float Columns are for floats
     */
    Float: "float",
    /**
     * Boolean Columns are for booleans
     */
    Boolean: "boolean",
} as const;

export type ColumnType = (typeof ColumnType)[keyof typeof ColumnType];
